source 'http://rubygems.org'

gem 'rails', '3.0.3'

gem 'haml'
gem 'haml-rails'
gem 'mongoid', '2.0.0.beta.20'
gem 'mongoid_slug', :require => 'mongoid/slug'
gem 'bson_ext', '1.1.4'
gem 'delayed_job'
gem 'delayed_job_mongoid'
gem 'open4'
gem 'jquery-rails'
gem 'stateflow'
gem 'hashie'
gem 'tinder'
gem 'simple_form'
gem 'devise'
gem 'cancan'

group :development, :test do
  gem 'rcov'
  gem 'steak', '~> 1.0.0'
  gem 'mongoid-rspec'
  gem 'capybara'
  gem 'launchy'
  gem 'ffaker'
  gem 'fabrication'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'database_cleaner', :git => 'git://github.com/bmabey/database_cleaner.git'
  # just what I like to use, comment these out if you don't want to use
  # them
  gem 'guard-rspec'
  gem 'growl'
  gem 'rails_best_practices'
  gem 'hirb'
  gem 'wirble'
  gem 'awesome_print', :require => 'ap'
end
